name = "Gaugefields"
uuid = "a461e10c-0d91-493e-bc41-027b226eee91"
authors = ["Akio Tomiya, Yuki Nagai <cometscome@gmail.com> and contributors"]
version = "0.6.12"

[deps]
CLIME_jll = "3c6ae550-c37b-5556-a07e-d40b4910cf1c"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JACC = "0979c8fe-16a4-4796-9b82-89a9f10403ea"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LatticeMatrices = "dd6a91e4-736f-4540-ac85-13822ca7b545"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PreallocatedArrays = "f9710d63-ac16-4fea-bcef-3ac1fb623b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Wilsonloop = "f3c8d4fe-2f22-401d-8228-e6a01d7a1d02"

[compat]
Distributions = "0.25"
EzXML = "1"
InteractiveUtils = "1"
JACC = "0.5.0"
JLD2 = "0.4, 0.5"
MPI = "0.20"
NPZ = "0.4"
PreallocatedArrays = "0.0.1"
Requires = "1"
StableRNGs = "1"
StaticArrays = "1.9.14"
Wilsonloop = "0.1.3"
LatticeMatrices = "0.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
